### ISSUE TITLE
can we connect to soa schema without installing database server?

### ISSUE THREAD

**Issue by supriyawishesu** [biemond/biemond-wls#10]
Hi Biemond,

we have our own database server. And they created oracle SID and schemas too. So can we use those  database schema to connect to database server.  without installing oradb module. when creating soa domain.

Please let me know.  Help me

**Comment by biemond** [comment]
That wil work,

then you only need to run rcu of the oradb module 

oradb::rcu{     'DEV2_PS6':
                 rcuFile          => 'ofm_rcu_linux_11.1.1.7.0_disk1_1of1.zip',
                 product          => 'webcenter',
                 version          => '11.1.1.7',
                 oracleHome       => '/oracle/product/11.2/db',
                 user             => 'oracle',
                 group            => 'dba',
                 downloadDir      => '/install',
                 action           => 'create',
                 dbServer         => 'dbagent1.alfa.local:1521',
                 dbService        => 'test.oracle.com',
                 sysPassword      => 'Welcome01',
                 schemaPrefix     => 'DEV',
                 tempTablespace   => 'TEMP',
                 reposPassword    => 'Welcome02',
}
