### ISSUE TITLE
Hi biemond

### ISSUE THREAD

**Issue by supriyawishesu** [biemond/biemond-wls#3]
For tuning up the jdk7 we want to install jdk7 on /u01/app/oracle/product/jdk
and ownsership is root:oinstall where I need to modify those parameters. any help will be appreciated.

Please let me know
Thank You

**Comment by biemond** [comment]
Hi,

You need to change the following install7.pp and javaexec.pp manifests. change /usr/java/ to your /u01/app/oracle/product/ folder 

and change $group = 'root' in install7.pp

hope this helps

**Comment by supriyawishesu** [comment]
Hi biemond,

Can we change directly inside the module which is created by you?

**Comment by biemond** [comment]
No problem,

I Don't do many updates on this module ( very stable)   or you need to backup and compare your changes before you update this module ( there is no auto update which will remove you changes. ) 

thanks

**Comment by biemond** [comment]
But if you want to use this with my wls module than this module won't work. ( this will use /usr/java )
you need to switch to my orawls module  
with my orawls module you can provide the full path of the jdk like 
jdk_home_dir => '/usr/java/jdk1.7.0_45'

**Comment by supriyawishesu** [comment]
Hi biemond,
After modifying these module directly, how do i need to include in the wls
module I mean the examples which you written for wls like just say

Include Jdk
and then jdk7::install {
.....
..... Like this in wls

**Comment by biemond** [comment]
Hi,

you can look at my vagrant box , this has full working examples like this one 
https://github.com/biemond/biemond-wls-vagrant-12.1.2/blob/master/puppet/manifests/site.pp

or look at all the examples in the wls module folder 

thanks

**Comment by supriyawishesu** [comment]
Hi biemond ,

Can't I change the /usr/java  in install7.pp and javaexec.pp and place in
/u01/app/oracle in jdk7 module and include in the wls module for 10.3
version of wls

**Comment by biemond** [comment]
yep that will work ( only internal are changed ) but wls module won't look in /u01/app/oracle but in /usr/java
which example or vagrant box did you use?

**Comment by supriyawishesu** [comment]
It is example 3 I guess

**Comment by supriyawishesu** [comment]
Hi biemond,

It is example 3 wls 12.1.2 but I am using wls 10.3 version

**Comment by supriyawishesu** [comment]
Hi biemond,

for installing weblogic 10.3.6 which module is the best one?. I mean
biemond/wls or biemond/ora-wls?
Please let me know.

Appreciate your help.

Thank You,
Supriya

**Comment by biemond** [comment]
biemond/ora-wls is the best one especially when using a different JDK home.

**Comment by supriyawishesu** [comment]
Hi biemond ,

Is there any way to integrate different Jdk module into wls module?

Thank you,
Supriya

**Comment by biemond** [comment]
No problem there is no dependecy between the jdk and wls module, only for wls you need to install the jdk in /usr/java
