### ISSUE TITLE
hi biemond

### ISSUE THREAD

**Issue by wishesu** [biemond/biemond-wls#4]
I biemond,
how can I integrate different jdk module which is written by others into wls modules.

Please help me.

**Comment by biemond** [comment]
Hi,

no problem , 

with my wls module you need to install the jdk to /usr/java.
or with my new orawls module you can provide the full path of the jdk like 
jdk_home_dir => '/usr/java/jdk1.7.0_45'

there is no hard reference to my jdk7 module module, only make sure you think about the lack of entropy

thanks
