### ISSUE TITLE
hi biemond,

### ISSUE THREAD

**Issue by supriyawishesu** [biemond/biemond-wls#5]
Hi, 

I am trying to install weblogic and soa. no domain creation. I wrote like this.but it is not installing it.
 class weblogic{

include java_jdk
include wls1036_6
# include orautils
# include wls1036_domain_6

class{'orautils':
        osOracleHomeParam      => "/u01/app/oracle",
        oraInventoryParam      => "/u01/app/oracle/oraInventory",
        osDomainTypeParam      => "soa",
        osLogFolderParam       => "/u01/app/oracle/logs",
        osDownloadFolderParam  => "/u01/app/oracle/install",
        osMdwHomeParam         => "/u01/app/oracle/product/Middleware",
        osWlHomeParam          => "/u01/app/oracle/product/Middleware/wlserver_10.3",
        oraUserParam           => "oracle",
        osDomainParam          => "osbSoaDomain",
        osDomainPathParam      => "/u01/app/oracle/product/Middleware/user_projects/domains/osbSoaDomain",
        nodeMgrPathParam       => "/u01/app/oracle/product/Middleware/wlserver_10.3/server/bin",
        nodeMgrPortParam       => 5556,
        wlsUserParam           => "weblogic",
        wlsPasswordParam       => "weblogic1",
        wlsAdminServerParam    => "AdminServer",
  }
class wls1036_6{

   class { 'wls::urandomfix' :}

   $jdkWls11gJDK = 'jdk1.7.0_25'
   $wls11gVersion = "1036"

   $puppetDownloadMntPoint = "/stage/WLS1036/"

   $osOracleHome = "/u01/app/oracle"
   $osMdwHome    = "/u01/app/oracle/product/Middleware"
   $osWlHome     = "/u01/app/oracle/product/Middleware/wlserver_10.3"
   $user         = "oracle"
   $group        = "oinstall"
   $downloadDir  = "/u01/app/oracle/install"
   $logDir       = "/u01/app/oracle/logs"

```
}
```
# set the defaults

  Wls::Installwls {
    version                => $wls11gVersion,
    fullJDKName            => $jdkWls11gJDK,
    oracleHome             => $osOracleHome,
    mdwHome                => $osMdwHome,
    user                   => $user,
 group                  => $group,
    downloadDir            => $downloadDir,
    puppetDownloadMntPoint => $puppetDownloadMntPoint,
  }
 Wls::Installsoa {
    mdwHome                => $osMdwHome,
    wlHome                 => $osWlHome,
    oracleHome             => $osOracleHome,
    fullJDKName            => $jdkWls11gJDK,
    user                   => $user,
    group                  => $group,
    downloadDir            => $downloadDir,
    puppetDownloadMntPoint => $puppetDownloadMntPoint,
  }

  # install
  wls::installwls{'11gPS5':
}

 wls::installsoa{'soaPS6':
     soaFile1      => 'ofm_soa_generic_11.1.1.7.0_disk1_1of2.zip',
     soaFile2      => 'ofm_soa_generic_11.1.1.7.0_disk1_2of2.zip',
     require       =>  Wls::Installwls['11gPS5'],
   }

}

Please help me

**Comment by biemond** [comment]
Can you do "puppet agent --test" and paste the last output

Thanks

**Comment by supriyawishesu** [comment]
hi biemond,

I did _puppet apply iniit.pp --debug_

Debug: Loaded state in 0.17 seconds
Debug:
/Stage[main]/Java_jdk/File[/u01/app/oracle/product/java/jdk1.7.0_25.tar.gz]/require:
requires File[/u01/app/oracle/product/java]
Debug:
/Stage[main]/Java_jdk/File[/u01/app/oracle/product/java/jdk1.7.0_25.tar.gz]/before:
requires Exec[untar jdk1.7.0_25.tar.gz]
Debug: /Stage[main]/Java_jdk/Exec[untar jdk1.7.0_25.tar.gz]/subscribe:
subscribes to File[/u01/app/oracle/product/java/jdk1.7.0_25.tar.gz]
Debug: /Stage[main]/Java_jdk/Exec[untar jdk1.7.0_25.tar.gz]/before:
requires File[/u01/app/oracle/product/java/jdk1.7.0_25]
Debug: /Stage[main]/Wls::Urandomfix/Exec[set urandom
/etc/sysconfig/rngd]/require: requires Package[rng-tools]
Debug: /Stage[main]/Wls::Urandomfix/Service[start rngd service]/require:
requires Exec[set urandom /etc/sysconfig/rngd]
Debug: /Stage[main]/Wls::Urandomfix/Exec[chkconfig rngd]/require: requires
Service[start rngd service]
Debug: /Stage[main]/Orautils/File[/opt/scripts/wls]/require: requires
File[/opt/scripts]
Debug: /Stage[main]/Orautils/File[showStatus.sh]/require: requires
File[/opt/scripts/wls]
Debug: /Stage[main]/Orautils/File[stopNodeManager.sh]/require: requires
File[/opt/scripts/wls]
Debug: /Stage[main]/Orautils/File[cleanOracleEnvironment.sh]/require:
requires File[/opt/scripts/wls]
Debug: /Stage[main]/Orautils/File[startNodeManager.sh]/require: requires
File[/opt/scripts/wls]
Debug: /Stage[main]/Orautils/File[startWeblogicAdmin.sh]/require: requires
File[/opt/scripts/wls]
Debug: /Stage[main]/Orautils/File[stopWeblogicAdmin.sh]/require: requires
File[/opt/scripts/wls]
Debug: /Stage[main]/Weblogic/Wls::Installsoa[soaPS6]/require: requires
Wls::Installwls[11gPS5]
Debug: /Stage[main]/Java_jdk/Exec[untar jdk1.7.0_25.tar.gz]: Autorequiring
File[/u01/app/oracle/product/java]
Debug:
/Stage[main]/Java_jdk/File[/u01/app/oracle/product/java/jdk1.7.0_25]:
Autorequiring File[/u01/app/oracle/product/java]
Info: Applying configuration version '1392746352'
Debug: Exec[create /u01/app/oracle/product/java directory](provider=posix):
Executing 'mkdir -p /u01/app/oracle/product/java'
Debug: Executing 'mkdir -p /u01/app/oracle/product/java'
Notice: /Stage[main]/Java_jdk/Exec[create /u01/app/oracle/product/java
directory]/returns: executed successfully
Debug: /Stage[main]/Java_jdk/Exec[create /u01/app/oracle/product/java
directory]: The container Class[Java_jdk] will propagate my refresh event
Debug: Prefetching yum resources for package
Debug: Executing '/bin/rpm --version'
Debug: Executing '/bin/rpm -qa --nosignature --nodigest --qf '%{NAME}
%|EPOCH?{%{EPOCH}}:{0}| %{VERSION} %{RELEASE} %{ARCH} :DESC: %{SUMMARY}\n''
Debug: Class[Java_jdk]: The container Stage[main] will propagate my refresh
event
Debug: Exec[set urandom /etc/sysconfig/rngd](provider=posix): Executing
check '/bin/grep '^EXTRAOPTIONS="-r /dev/urandom -o /dev/random -b"'
/etc/sysconfig/rngd'
Debug: Executing '/bin/grep '^EXTRAOPTIONS="-r /dev/urandom -o /dev/random
-b"' /etc/sysconfig/rngd'
Debug: /Stage[main]/Wls::Urandomfix/Exec[set urandom
/etc/sysconfig/rngd]/unless: EXTRAOPTIONS="-r /dev/urandom -o /dev/random
-b"
Debug: Executing '/sbin/service rngd status'
Debug: Executing '/sbin/chkconfig rngd'
Debug: Exec[chkconfig rngd](provider=posix): Executing check 'chkconfig |
/bin/grep 'rngd''
Debug: Executing 'chkconfig | /bin/grep 'rngd''
Debug: /Stage[main]/Wls::Urandomfix/Exec[chkconfig rngd]/unless:
rngd                   0:off   1:off   2:on    3:on    4:on    5:on    6:off
Debug: Finishing transaction 26946400
Debug: Storing state
Debug: Stored state in 0.22 seconds
Notice: Finished catalog run in 3.24 seconds
Debug: Using settings: adding file resource 'rrddir':
'File[/var/opt/lib/pe-puppet/rrd]{:path=>"/var/opt/lib/pe-puppet/rrd",
:mode=>"750", :owner=>"pe-puppet", :group=>"pe-puppet",
:ensure=>:directory, :loglevel=>:debug, :links=>:follow, :backup=>false}'
Debug: Finishing transaction 28456160
Debug: Received report to process from dot-pap-spr-d03.local
Debug: Processing report from dot-pap-spr-d03.local with processor
Puppet::Reports::Store

here is the output.

Please help me

**Comment by biemond** [comment]
Did you add a node with your server name to the init.pp within this node you call the other classes in the right order . it looks like you only call the jdk class

**Comment by supriyawishesu** [comment]
hi biemond,

I am installing this locally. I included wls and wls1036_6 too. see I
defined it below. Please let me know.

class weblogic{

include java_jdk,wls
include wls1036_6

**Comment by biemond** [comment]
I would expect something like this 

```
 node 'xxx.yourdomain {
   include java_jdk,wls
   include wls1036_6

   Class[java_jdk] -> Class[wls]  -> Class[wls1036_6] 
 } 
```

**Comment by supriyawishesu** [comment]
Hi Biemond,
- is this example working for you
  example_conf_4_weblogic_10.3.6_osb_soa_ps6.txt?.*

_Please let me know._

**Comment by biemond** [comment]
off course , but this a puppet master example and I assign in the dashboard the main class to a node 

which does the same as this code 

```
node 'xxx.yourdomain {
   include java_jdk,wls
   include wls1036_6

  Class[java_jdk] -> Class[wls]  -> Class[wls1036_6] 
} 
```

please follow first all these tutorial steps. This has nothing to do with my code
http://docs.puppetlabs.com/learning/index.html
