### ISSUE TITLE
Only SOA domain creation

### ISSUE THREAD

**Issue by supriyawishesu** [biemond/biemond-wls#6]
Hi Biemond,

Is there any way to create only SOA domain without using OSB and BPM?

Please help me.

Appreciate your help.

Thank You

**Comment by biemond** [comment]
Hi,

when you use 'soa' as value for the domain_template in the domain manifest
this are all the soa  options:  osb | osb_soa_bpm | osb_soa | soa | soa_bpm

**Comment by supriyawishesu** [comment]
Hi biemond,

To create SOA domain do I need to have OSB and BSUPatch too?

Please let me know

**Comment by biemond** [comment]
No need for the OSB install , BSU patch is a good thing else you got an unpatched wls version of 3 years ago
