### ISSUE TITLE
not able to install wls using non root user

### ISSUE THREAD

**Issue by supriyawishesu** [biemond/biemond-wls#8]
Hi biemond,

In puppet 3.2 I am trying to install wls using not root user. I edited the wls module and changed all user from root to oracle and oinstall.

when I am installing wls, I am having this issue let me know

Error: Failed to apply catalog: Parameter user failed on Exec[install wls 11g1036]: Only root can execute commands as other users at /etc/puppetlabs/puppet/environments/testing/modules/wls/manifests/installwls.pp:270
Wrapped exception:
Only root can execute commands as other users

**Comment by biemond** [comment]
Hi,

Default I run everything under Oracle ( puppet uses root and run it as oracle ) I only use it when I need to be root.   so in that case you can use sudo for this ( off course you need to provide permissions for oracle sudo )
